"""add_pgvector_rag

Revision ID: 36eb1e23b172
Revises: '33f1640954bd'
Create Date: 2026-08-13 03:38:15.548619

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "36eb1e23b172"
down_revision: str | None = "33f1640954bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_chunks",
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    )
    op.add_column(
        "knowledge_chunks",
        sa.Column(
            "fts_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_knowledge_chunks_embedding_hnsw",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_knowledge_chunks_fts",
        "knowledge_chunks",
        ["fts_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "knowledge_documents", sa.Column("content_hash", sa.String(length=64), nullable=False)
    )
    op.create_unique_constraint(
        op.f("uq_knowledge_documents_content_hash"), "knowledge_documents", ["content_hash"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_knowledge_documents_content_hash"), "knowledge_documents", type_="unique"
    )
    op.drop_column("knowledge_documents", "content_hash")
    op.drop_index("ix_knowledge_chunks_fts", table_name="knowledge_chunks", postgresql_using="gin")
    op.drop_index(
        "ix_knowledge_chunks_embedding_hnsw",
        table_name="knowledge_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_column("knowledge_chunks", "fts_vector")
    op.drop_column("knowledge_chunks", "embedding")
    # ### end Alembic commands ###
