FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

RUN npm ci --workspace=apps/console

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app/apps/console
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production \
    PORT=3000 \
    NEXT_TELEMETRY_DISABLED=1

COPY --from=builder --chown=node:node /app/apps/console/.next/standalone ./
COPY --from=builder --chown=node:node /app/apps/console/.next/static ./apps/console/.next/static

EXPOSE 3000

USER node

CMD ["node", "server.js"]
