apiVersion: v1
kind: Service
metadata:
  name: {{ include "incidentgraph.fullname" . }}-control-plane
  labels:
    {{- include "incidentgraph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.controlPlane.type }}
  ports:
    - port: {{ .Values.service.controlPlane.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: control-plane
